DELETE http://localhost:8080/events/4
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NDc5MjI1OTYsInVzZXJJZCI6MX0.4ddSANsrz_lr5oMvEejXaACpUS9pBDYfgjCKRumPNqQ
