DELETE http://localhost:8080/events/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NDc5MjA3MDIsInVzZXJJZCI6MX0.B5y02FVSqIOKJjdCoR10dFuji3gWhy7r-RbriTZW_zU
